Repository pypa/pip-audit, pull requests merged in 2021-11, with the labels that each got.

#91 CONTRIBUTING, README: add contributing documentation
  CONTRIBUTING.md
  README.md
Labels: C:docs

#100 service/pypi: fix cache bugs
  pip_audit/service/pypi.py
Labels: bug, C:dep-sources

#101 Makefile, CONTRIBUTING: small testing niceties
  CONTRIBUTING.md
  Makefile
Labels: documentation, C:tests

#95 pip_audit: Update state feedback when fetching metadata
  pip_audit/dependency_source/resolvelib/pypi_provider.py
  pip_audit/virtual_env.py
  test/dependency_source/test_resolvelib.py
Labels: C:cli, C:dep-sources

#106 CI, Makefile, README: enforce `pip-audit --help` changes
  .github/workflows/ci.yml
  Makefile
  README.md
Labels: C:docs, C:cicd

#110 doc: Document all public APIs
  .bump
  CONTRIBUTING.md
  Makefile
  pip_audit/__init__.py
  pip_audit/_version.py
  pip_audit/audit.py
  pip_audit/cli.py
  pip_audit/dependency_source/__init__.py
  pip_audit/dependency_source/interface.py
  pip_audit/dependency_source/pip.py
  pip_audit/dependency_source/requirement.py
  pip_audit/dependency_source/resolvelib/__init__.py
  pip_audit/dependency_source/resolvelib/pypi_provider.py
  pip_audit/dependency_source/resolvelib/resolvelib.py
  pip_audit/format/__init__.py
  pip_audit/format/columns.py
  pip_audit/format/interface.py
  pip_audit/format/json.py
  pip_audit/service/__init__.py
  pip_audit/service/interface.py
  pip_audit/service/osv.py
  pip_audit/service/pypi.py
  pip_audit/state.py
  pip_audit/util.py
  pip_audit/virtual_env.py
  pyproject.toml
  setup.py
Labels: C:docs

#112 dependabot: configuration
  .github/dependabot.yml
Labels: C:cicd

#114 Fix setup.py requirements for dataclasses. dataclasses is part of Py3.7+
  setup.py
Labels: dependencies

#118 test: add __init__.py files
  test/__init__.py
  test/service/__init__.py
Labels: C:tests

#109 pip_audit: initial SBOM support via CycloneDX
  README.md
  pip_audit/cli.py
  pip_audit/format/__init__.py
  pip_audit/format/cyclonedx.py
  setup.py
  test/format/test_cyclonedx.py
Labels: C:cli, C:output-formats

#128 Enable documentation builds, document doc builds
  CONTRIBUTING.md
  Makefile
  pip_audit/__init__.py
  pip_audit/_version.py
  pip_audit/dependency_source/resolvelib/resolvelib.py
  setup.py
Labels: C:docs, dependencies

#132 service/pypi: Use full cache path instead of directory name
  pip_audit/service/pypi.py
  test/service/test_pypi.py
Labels: bug, C:vuln-sources, C:tests

#133 pip_audit: Add timeout for network requests
  README.md
  pip_audit/cli.py
  pip_audit/dependency_source/resolvelib/pypi_provider.py
  pip_audit/dependency_source/resolvelib/resolvelib.py
  pip_audit/service/osv.py
  pip_audit/service/pypi.py
  test/dependency_source/test_resolvelib.py
  test/service/test_pypi.py
Labels: enhancement, C:cli

#129 github/workflows: add a docs workflow
  .github/workflows/docs.yml
  CONTRIBUTING.md
  pip_audit/__init__.py
  pip_audit/_audit.py
  pip_audit/_cli.py
  pip_audit/_dependency_source/__init__.py
  pip_audit/_dependency_source/interface.py
  pip_audit/_dependency_source/pip.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_dependency_source/resolvelib/__init__.py
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  pip_audit/_format/__init__.py
  pip_audit/_format/columns.py
  pip_audit/_format/cyclonedx.py
  pip_audit/_format/interface.py
  pip_audit/_format/json.py
  pip_audit/_service/__init__.py
  pip_audit/_service/interface.py
  pip_audit/_service/osv.py
  pip_audit/_service/pypi.py
  pip_audit/_state.py
  pip_audit/_util.py
  pip_audit/_virtual_env.py
  pyproject.toml
  setup.py
  test/conftest.py
  test/dependency_source/test_interface.py
  test/dependency_source/test_pip.py
  test/dependency_source/test_requirement.py
  test/dependency_source/test_resolvelib.py
  test/format/conftest.py
  test/format/test_columns.py
  test/format/test_cyclonedx.py
  test/format/test_json.py
  test/service/conftest.py
  test/service/test_osv.py
  test/service/test_pypi.py
  test/test_audit.py
  test/test_virtual_env.py
Labels: C:docs, C:cicd, do not merge

#134 _cli, README: fix a small `pip-audit --help` typo
  README.md
  pip_audit/_cli.py
Labels: C:cli

#136 pip_audit/_state: truncate progress lines if they wrap
  pip_audit/_state.py
Labels: C:cli
