Repository pypa/pip-audit, pull requests merged in 2021-12, with the labels that each got.

#146 README, _cli: Add a `-S`, `--strict` mode
  README.md
  pip_audit/_cli.py
  pip_audit/_dependency_source/pip.py
  pip_audit/_service/pypi.py
  test/dependency_source/test_pip.py
  test/service/test_pypi.py
Labels: C:cli

#143 CONTRIBUTING, ISSUE_TEMPLATE: add more advice
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
Labels: C:docs

#149 Stabilization!
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  setup.py
Labels: C:docs

#153 _cli: Fix the behavior of the `--desc` flag
  CHANGELOG.md
  README.md
  pip_audit/_cli.py
Labels: bug, C:cli

#158 test, Makefile: Run MyPy across unit tests
  Makefile
  test/dependency_source/test_pip.py
  test/dependency_source/test_resolvelib.py
  test/format/conftest.py
  test/service/test_osv.py
  test/service/test_pypi.py
  test/test_audit.py
Labels: component:tests, component:cicd

#148 pip, _cli: Add `--path` argument to mirror `pip list`
  CHANGELOG.md
  README.md
  pip_audit/_cli.py
  pip_audit/_dependency_source/pip.py
  setup.py
  test/dependency_source/test_pip.py
Labels: component:cli, component:dep-sources

#173 Add a module entrypoint
  CHANGELOG.md
  README.md
  pip_audit/__main__.py
Labels: component:cli

#174 _state: clear the spinner entirely when done
  CHANGELOG.md
  pip_audit/_state.py
Labels: component:cli

#175 pip_audit, test: make Python runtime version retrieval more resilient
  CHANGELOG.md
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_util.py
  test/test_util.py
Labels: component:dep-sources

#183 README: document the security model
  README.md
Labels: component:docs

#166 Don't explode sdists before installing them
  CHANGELOG.md
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_util.py
  pip_audit/_virtual_env.py
Labels: bug, component:dep-sources, performance

#189 README: highlight a few features
  README.md
Labels: component:docs

#178 pypi: add a retry loop for cache updates
  CHANGELOG.md
  pip_audit/_service/pypi.py
Labels: plat:windows, performance

#188 pip_audit, test: generalize caching middleware
  pip_audit/_cache.py
  pip_audit/_cli.py
  pip_audit/_service/osv.py
  pip_audit/_service/pypi.py
  test/conftest.py
  test/service/conftest.py
  test/service/test_osv.py
  test/service/test_pypi.py
  test/test_cache.py
Labels: enhancement, performance

#192 Refactor `AuditState`
  pip_audit/_cli.py
  pip_audit/_dependency_source/pip.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  pip_audit/_state.py
  pip_audit/_virtual_env.py
  test/test_state.py
Labels: refactoring

#194 pip_audit, test: perform even more PyPI caching
  pip_audit/_cli.py
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  test/dependency_source/test_resolvelib.py
Labels: enhancement, component:dep-sources, performance

#196 setup: pip-api >= 0.0.26
  CHANGELOG.md
  setup.py
Labels: dependencies

#200 README: document third-party packages
  README.md
Labels: component:docs

#201 README, _cli: document exit codes, allow suppression
  README.md
Labels: component:cli, component:docs

#205 setup: use CacheControl[filecache]
  setup.py
Labels: dependencies
