Repository pypa/pip-audit, pull requests merged in 2022-09, with the labels that each got.

#361 meta: update trailofbits slugs to pypa
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  pyproject.toml
Labels: chore

#362 pre-commit: update URL to pypa
  .pre-commit-config.yaml
Labels: chore

#363 Prepare 2.4.4
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#364 Add details for running against pipenv projects
  README.md
Labels: component:docs

#367 ✨ Enable OpenSSF Scorecard code scanning alert and badge
  .github/workflows/scorecards.yml
  README.md
Labels: component:cicd
