Repository pypa/pip-audit, pull requests merged in 2022-07, with the labels that each got.

#318 PyPI: Adjust JSON API use to handle upstream changes
  CHANGELOG.md
  pip_audit/_service/pypi.py
  test/service/test_pypi.py
Labels: component:vuln-sources

#319 Prep 2.4.1
  CHANGELOG.md
  pip_audit/__init__.py
Labels: chore

#316 workflows: Sign releases with `sigstore-python`
  .github/workflows/release.yml
Labels: component:cicd, github_actions

#320 requirement: Parse requirements using `pip-requirements-parser` instead of `pip-api`
  pip_audit/_dependency_source/requirement.py
  pyproject.toml
  test/dependency_source/test_requirement.py
Labels: component:dep-sources, component:fixes

#323 OSV, PyPI: Do not use "details" field for vuln summaries
  CHANGELOG.md
  pip_audit/_service/osv.py
  pip_audit/_service/pypi.py
  test/service/test_osv.py
  test/service/test_pypi.py
Labels: component:vuln-sources

#324 Bump to 2.4.2
  CHANGELOG.md
  pip_audit/__init__.py
Labels: chore

#325 CHANGELOG: fix link
  CHANGELOG.md
Labels: chore

#331 requirement: Skip requirements without an inferred name/specifier
  CHANGELOG.md
  pip_audit/_dependency_source/requirement.py
  test/dependency_source/test_requirement.py
Labels: component:dep-sources

#332 pip-audit: bump to 2.4.3
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#333 README: bump gh-action-pip-audit version
  README.md
Labels: chore

#337 pyproject: update authors, classifiers
  pyproject.toml
Labels: chore

#338 service/interface: newtype vulnerability IDs
  pip_audit/_service/interface.py
Labels: component:vuln-sources, refactoring

#339 CLI: better meta-variables
  README.md
  pip_audit/_cli.py
Labels: component:cli, refactoring
