Repository pypa/pip-audit, pull requests merged in 2022-12, with the labels that each got.

#425 README: clarify pip-audit behavior around exit codes
  README.md
Labels: component:docs

#429 pyproject.toml: Unpin `packaging` now that `pip-requirements-parser` pins it
  pyproject.toml
Labels: dependencies

#432 CLI: Don't create empty files on failure
  CHANGELOG.md
  README.md
  pip_audit/_cli.py
Labels: component:cli

#435 treewide: prep 2.4.9
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#436 CHANGELOG: fix a link typo
  CHANGELOG.md
Labels: chore

#444 treewide: replace flake8 with ruff
  .flake8
  CONTRIBUTING.md
  Makefile
  pip_audit/_audit.py
  pip_audit/_cli.py
  pip_audit/_dependency_source/interface.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_format/columns.py
  pip_audit/_service/osv.py
  pip_audit/_service/pypi.py
  pip_audit/_virtual_env.py
  pyproject.toml
  test/dependency_source/test_pyproject.py
  test/dependency_source/test_requirement.py
Labels: chore

#447 pip_audit, test: handle invalid requires-python specifiers
  CHANGELOG.md
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  test/dependency_source/resolvelib/test_resolvelib.py
Labels: component:dep-sources

#449 pip_audit, test: `ruff` fixes
  pip_audit/_format/columns.py
  pip_audit/_format/markdown.py
  pip_audit/_subprocess.py
  test/dependency_source/resolvelib/test_resolvelib.py
  test/dependency_source/test_pip.py
  test/format/test_columns.py
  test/format/test_markdown.py
Labels: chore

#452 _cli: refactor logging
  README.md
  pip_audit/_cli.py
Labels: component:cli, refactoring

#454 Include setuptools in upgrade set
  CHANGELOG.md
  pip_audit/_virtual_env.py
Labels: bug, component:dep-sources

#451 pip_audit, test: warn on Python path confusion
  CHANGELOG.md
  pip_audit/_cache.py
  pip_audit/_dependency_source/pip.py
  test/dependency_source/test_pip.py
Labels: component:dep-sources

#456 CHANGELOG: fix entry
  CHANGELOG.md
Labels: component:docs, chore
