Repository pypa/pip-audit, pull requests merged in 2022-06, with the labels that each got.

#292 pyproject: add missing toml deps
  pyproject.toml
Labels: upstream, component:cicd, dependencies

#295 pyproject: relax cyclonedx version range
  pyproject.toml
Labels: dependencies

#300 Respect `--cache-dir` and other flags when auditing project directories
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  pip_audit/_cli.py
Labels: component:cli, component:dep-sources

#297 requirement, test: Correct `--fix` for subdependencies in requirements files
  CHANGELOG.md
  pip_audit/_dependency_source/requirement.py
  test/dependency_source/test_requirement.py
Labels: component:cli, component:fixes

#301 README: link to the new GitHub Action
  README.md
Labels: component:docs

#306 dependabot: check for github actions updates
  .github/dependabot.yml
Labels: component:cicd

#304 README: Documentation improvements
  README.md
Labels: component:docs

#311 Refactor the release workflow
  .github/workflows/release.yml
  CONTRIBUTING.md
  Makefile
Labels: component:cicd

#313 pip_audit: 2.4.0
  CHANGELOG.md
  pip_audit/__init__.py
Labels: chore
