Repository pypa/pip-audit, pull requests merged in 2022-02, with the labels that each got.

#230 Bump minimum Python to 3.7
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  setup.py
Labels: dependencies

#232 pip_audit: dedupe vulnerability reports by alias
  CHANGELOG.md
  pip_audit/_audit.py
  pip_audit/_service/interface.py
  pip_audit/_service/osv.py
  pip_audit/_service/pypi.py
  test/conftest.py
  test/format/conftest.py
  test/service/test_interface.py
  test/service/test_osv.py
  test/service/test_pypi.py
  test/test_audit.py
  test/test_fix.py
Labels: enhancement, component:vuln-sources

#236 Makefile: predicate venv on setup.py
  Makefile
Labels: refactoring

#238 _cli, resolvelib: Support for custom indices
  CHANGELOG.md
  README.md
  pip_audit/_cli.py
  pip_audit/_dependency_source/__init__.py
  pip_audit/_dependency_source/resolvelib/__init__.py
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  test/dependency_source/test_resolvelib.py
Labels: component:dep-sources, do not merge

#244 pip_audit, test: allow editable packages to be skipped
  CHANGELOG.md
  README.md
  pip_audit/_cli.py
  pip_audit/_dependency_source/pip.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  setup.py
  test/dependency_source/test_pip.py
  test/dependency_source/test_resolvelib.py
Labels: enhancement, component:cli, component:dep-sources
