Repository pypa/pip-audit, pull requests merged in 2023-05, with the labels that each got.

#605 pyproject: add, pin requests
  CHANGELOG.md
  pyproject.toml
Labels: bug, dependencies

#606 chore: prep 2.5.5
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#607 CHANGELOG: fix entries
  CHANGELOG.md
Labels: chore

#617 pyproject: constrain urllib3
  CHANGELOG.md
  pyproject.toml
Labels: dependencies

#618 treewide: 2.5.6
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#627 simplified the usage of CycloneDx
  pip_audit/_format/cyclonedx.py
Labels: component:output-formats
