Repository pypa/pip-audit, pull requests merged in 2023-01, with the labels that each got.

#461 pip_audit: `ruff` fixes
  pip_audit/_cache.py
Labels: component:cicd, chore

#465 pyproject: constrain ruff
  pyproject.toml
Labels: component:cicd, chore

#469 build, workflows: optimize linting
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  Makefile
  pyproject.toml
Labels: component:cicd, chore

#474 Prep 2.4.13
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#483 Makefile: Windows accommodations
  Makefile
Labels: chore

#485 Refactor docs build, replace pdoc3
  .github/workflows/docs.yml
  Makefile
  pyproject.toml
Labels: component:docs, component:cicd, chore

#477 Fix handling of prerelease-only resolutions
  CHANGELOG.md
  pip_audit/_cli.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  test/dependency_source/resolvelib/test_resolvelib.py
Labels: component:dep-sources

#495 docs: update example of using pip-audit with pipenv
  README.md
Labels: component:docs

#494 prep 2.4.14
  CHANGELOG.md
  pip_audit/__init__.py
Labels: chore

#496 pre-commit: bump pip-audit versions
  .pre-commit-config.yaml
  README.md
Labels: chore

#488 resolvelib: Stop resolving requirements one-by-one
  CHANGELOG.md
  pip_audit/_dependency_source/interface.py
  pip_audit/_dependency_source/pyproject.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  test/dependency_source/resolvelib/test_pypi_provider.py
  test/dependency_source/resolvelib/test_resolvelib.py
  test/dependency_source/test_pyproject.py
  test/dependency_source/test_requirement.py
Labels: component:dep-sources

#505 pyproject.toml: Don't check for line-length with `ruff` since we're reformatting with `black`
  pyproject.toml
Labels: refactoring

#509 prep 2.4.15
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore
