Repository pypa/pip-audit, pull requests merged in 2023-06, with the labels that each got.

#628 pyproject: bump CacheControl
  pip_audit/_cache.py
  pyproject.toml
Labels: dependencies, chore

#626 Reintroduce dependency optimization
  CHANGELOG.md
  README.md
  pip_audit/_cli.py
  pip_audit/_dependency_source/__init__.py
  pip_audit/_dependency_source/interface.py
  pip_audit/_dependency_source/requirement.py
  test/dependency_source/test_requirement.py
Labels: component:dep-sources

#640 CHANGELOG: fix link
  CHANGELOG.md
Labels: chore
