Repository pypa/pip-audit, pull requests merged in 2023-03, with the labels that each got.

#523 treewide: Use `pip install` for dependency resolution
  pip_audit/_cli.py
  pip_audit/_dependency_source/__init__.py
  pip_audit/_dependency_source/interface.py
  pip_audit/_dependency_source/pyproject.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_dependency_source/resolvelib/__init__.py
  pip_audit/_dependency_source/resolvelib/pypi_provider.py
  pip_audit/_dependency_source/resolvelib/resolvelib.py
  pip_audit/_state.py
  pip_audit/_subprocess.py
  pip_audit/_virtual_env.py
  pyproject.toml
  test/dependency_source/resolvelib/__init__.py
  test/dependency_source/resolvelib/test_pypi_provider.py
  test/dependency_source/resolvelib/test_resolvelib.py
  test/dependency_source/test_interface.py
  test/dependency_source/test_pyproject.py
  test/dependency_source/test_requirement.py
  test/test_state.py
  test/test_virtual_env.py
Labels: component:dep-sources

#536 pip_audit: handle subprocess streams more cleanly
  CHANGELOG.md
  pip_audit/_subprocess.py
  pip_audit/_virtual_env.py
  test/test_virtual_env.py
Labels: component:dep-sources, refactoring, chore

#543 Prep 2.5.0
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#549 workflows/release: use OIDC exchange
  .github/workflows/release.yml
Labels: component:cicd, chore

#551 requirement: Close temporary files before passing them to `pip`
  CHANGELOG.md
  pip_audit/_dependency_source/requirement.py
  test/dependency_source/test_requirement.py
Labels: component:dep-sources

#554 Prep 2.5.1
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#572 _subprocess: perform invalid UTF-8 substitution
  CHANGELOG.md
  pip_audit/_subprocess.py
Labels: component:dep-sources

#576 Prep 2.5.3
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore

#565 _dependency_source, _cli, test: Do not override `pip.conf` unless explicitly specified via flags
  CHANGELOG.md
  README.md
  pip_audit/_cli.py
  pip_audit/_dependency_source/pyproject.py
  pip_audit/_dependency_source/requirement.py
  pip_audit/_virtual_env.py
  test/dependency_source/test_requirement.py
Labels: enhancement, component:dep-sources
