Repository pypa/pip-audit, pull requests merged in 2024-04, with the labels that each got.

#759 README: fixup troubleshooting docs based on #742
  README.md
Labels: component:docs

#757 Many tests failing on Windows
  CHANGELOG.md
  pip_audit/_dependency_source/pyproject.py
  pip_audit/_dependency_source/requirement.py
  test/conftest.py
  test/dependency_source/test_requirement.py
  test/test_cache.py
  test/test_cli.py
Labels: needs-response

#762 CHANGELOG: record #756
  CHANGELOG.md
Labels: chore

#771 prep 2.7.3
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  pip_audit/__init__.py
Labels: chore
